### ISSUE TITLE
Update to Latest API Version?

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/linkedin-tag#8]
The Latest API version is 2024-05: https://learn.microsoft.com/en-us/linkedin/marketing/versioning?view=li-lms-2024-05

I see this Tag Template is using a really old version: [2023-04](https://github.com/stape-io/linkedin-tag/blob/main/template.tpl#L442)

Any plans to update it?

**Comment by Bukashk0zzz** [comment]
Added to backlog

**Comment by Bukashk0zzz** [comment]
Done
